(function () {
  if (!document.getElementById('adminPortal')) return;
  var storeKey = 'rt-business-desk-v1';
  var db = readStore();
  var $ = function (selector, root) { return (root || document).querySelector(selector); };
  var $$ = function (selector, root) { return Array.prototype.slice.call((root || document).querySelectorAll(selector)); };
  var money = new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 });

  function seed() { return { inventory: [], sales: [] }; }
  function readStore() { try { return Object.assign(seed(), JSON.parse(localStorage.getItem(storeKey)) || {}); } catch (_) { return seed(); } }
  function saveStore() { localStorage.setItem(storeKey, JSON.stringify(db)); }
  function today() { return new Date().toISOString().slice(0, 10); }
  function makeId(prefix) { return prefix + '-' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6); }
  function invoiceNumber() { return 'RT-' + new Date().getFullYear() + '-' + String(db.sales.length + 1).padStart(4, '0'); }
  function number(value) { return Number(value) || 0; }
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/[&<>'"]/g, function (character) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]; }); }
  function formatDate(value) { return value ? new Date(value + 'T12:00:00').toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' }) : ''; }
  function setMessage(selector, message, isError) { var node = $(selector); if (node) { node.textContent = message || ''; node.classList.toggle('error', !!isError); } }

  function request(path, options) {
    options = options || {};
    return fetch(path, { method: options.method || 'GET', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: options.body ? JSON.stringify(options.body) : undefined })
      .then(function (response) { return response.json().catch(function () { return {}; }).then(function (body) { if (!response.ok) { var error = new Error(body.error || 'Request failed.'); error.status = response.status; throw error; } return body; }); });
  }
  function showTab(tab) { $$('.admin-tab-btn').forEach(function (button) { button.classList.toggle('active', button.dataset.adminTab === tab); }); $$('[data-admin-panel]').forEach(function (panel) { panel.hidden = panel.dataset.adminPanel !== tab; }); }
  function openPortal() { $('#ownerGate').hidden = true; $('#adminPortal').hidden = false; $('#adminDate').textContent = new Date().toLocaleDateString('en-NG', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }); renderAll(); }
  function closePortal() { window.location.href = 'index.html'; }
  function startOwnerAccess() { request('/api/auth/session').then(openPortal).catch(function () { $('#ownerGate').hidden = false; $('#ownerEmail').focus(); }); }
  function signOut() { request('/api/auth/logout', { method: 'POST', body: {} }).catch(function () {}).finally(function () { closePortal(); $('#ownerGate').hidden = true; setMessage('#ownerLoginMessage', 'You have signed out.'); }); }

  function lineMarkup(item) {
    var options = '<option value="">Select item</option>' + db.inventory.map(function (product) { return '<option value="' + product.id + '"' + (item && item.productId === product.id ? ' selected' : '') + '>' + escapeHtml(product.name) + ' (' + product.quantity + ' in stock)</option>'; }).join('');
    return '<div class="sale-line"><label>Product<select class="sale-product" required>' + options + '</select></label><label>Quantity<input class="sale-quantity" required type="number" min="1" step="1" value="' + (item ? item.quantity : 1) + '"></label><label>Line total<div class="sale-line-total">0</div></label><button class="row-action remove-sale-line" type="button">Remove</button></div>';
  }
  function addSaleLine(item) { $('#saleLines').insertAdjacentHTML('beforeend', lineMarkup(item)); updateSaleTotals(); }
  function updateSaleTotals() { var total = 0; $$('.sale-line').forEach(function (line) { var product = db.inventory.find(function (candidate) { return candidate.id === $('.sale-product', line).value; }); var amount = product ? number($('.sale-quantity', line).value) * number(product.price) : 0; $('.sale-line-total', line).textContent = money.format(amount); total += amount; }); $('#saleGrandTotal').textContent = 'Total: ' + money.format(total); return total; }
  function refreshSaleLines() { var previous = $$('.sale-line').map(function (line) { return { productId: $('.sale-product', line).value, quantity: number($('.sale-quantity', line).value) || 1 }; }); $('#saleLines').innerHTML = ''; (previous.length ? previous : [null]).forEach(addSaleLine); }

  function renderInventory() {
    $('#inventoryBody').closest('table').querySelector('thead tr').innerHTML = '<th>Item</th><th>SKU</th><th>Last stocked</th><th>Stock</th><th>Cost</th><th>Selling price</th><th></th>';
    $('#inventoryBody').innerHTML = db.inventory.length ? db.inventory.map(function (item) { var low = item.quantity <= item.reorderAt; return '<tr><td><strong>' + escapeHtml(item.name) + '</strong></td><td>' + escapeHtml(item.sku || '-') + '</td><td>' + (item.stockedDate ? formatDate(item.stockedDate) : '-') + '</td><td><span class="stock-pill ' + (low ? 'low' : '') + '">' + item.quantity + ' units' + (low ? ' - reorder' : '') + '</span></td><td>' + (item.cost ? money.format(item.cost) : '-') + '</td><td>' + money.format(item.price) + '</td><td><button class="row-action" type="button" data-restock="' + item.id + '">Restock</button></td></tr>'; }).join('') : '<tr><td colspan="7" class="admin-muted">No inventory yet. Add your first product above.</td></tr>';
  }
  function renderSales() {
    var recent = db.sales.slice().reverse().slice(0, 6);
    $('#recentSalesBody').innerHTML = recent.length ? recent.map(function (sale) { return '<tr><td><strong>' + escapeHtml(sale.invoice) + '</strong></td><td>' + escapeHtml(sale.customer) + '</td><td>' + formatDate(sale.date) + '</td><td>' + money.format(sale.total) + '</td><td><button class="row-action" type="button" data-invoice="' + sale.id + '">View</button></td></tr>'; }).join('') : '<tr><td colspan="5" class="admin-muted">No sales recorded yet.</td></tr>';
    $('#invoiceBody').innerHTML = db.sales.length ? db.sales.slice().reverse().map(function (sale) { return '<tr><td><strong>' + escapeHtml(sale.invoice) + '</strong></td><td>' + escapeHtml(sale.customer) + '</td><td>' + formatDate(sale.date) + '</td><td>' + escapeHtml(sale.payment) + '</td><td>' + money.format(sale.total) + '</td><td><button class="row-action" type="button" data-invoice="' + sale.id + '">Print / view</button></td></tr>'; }).join('') : '<tr><td colspan="6" class="admin-muted">Invoices will appear here after you save a sale.</td></tr>';
  }
  function renderOverview() {
    var now = new Date(), todaySales = db.sales.filter(function (sale) { return sale.date === today(); }), monthSales = db.sales.filter(function (sale) { var date = new Date(sale.date + 'T12:00:00'); return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear(); }), total = function (sales) { return sales.reduce(function (sum, sale) { return sum + number(sale.total); }, 0); }, units = db.inventory.reduce(function (sum, item) { return sum + number(item.quantity); }, 0), low = db.inventory.filter(function (item) { return item.quantity <= item.reorderAt; });
    $('#metricToday').textContent = money.format(total(todaySales)); $('#metricTodayHint').textContent = todaySales.length + (todaySales.length === 1 ? ' transaction today' : ' transactions today'); $('#metricMonth').textContent = money.format(total(monthSales)); $('#metricMonthHint').textContent = monthSales.length + (monthSales.length === 1 ? ' transaction this month' : ' transactions this month'); $('#metricItems').textContent = db.inventory.length; $('#metricItemsHint').textContent = units + ' units in stock'; $('#metricLow').textContent = low.length;
    $('#lowStockList').innerHTML = low.length ? low.map(function (item) { return '<p style="margin:0 0 10px"><strong>' + escapeHtml(item.name) + '</strong><br><span class="stock-pill low">' + item.quantity + ' left - reorder at ' + item.reorderAt + '</span></p>'; }).join('') : 'No items need reordering.';
  }
  function renderAll() { renderOverview(); renderInventory(); renderSales(); refreshSaleLines(); }
  function showInvoice(id) { var sale = db.sales.find(function (record) { return record.id === id; }); if (!sale) return; var rows = sale.items.map(function (item) { return '<tr><td>' + escapeHtml(item.name) + '</td><td style="text-align:center">' + item.quantity + '</td><td style="text-align:right">' + money.format(item.price) + '</td><td style="text-align:right"><strong>' + money.format(item.total) + '</strong></td></tr>'; }).join(''); $('#invoicePaper').innerHTML = '<div class="invoice-header"><div class="invoice-logo">Ruach &amp; Terra<span>Reality Ltd.</span></div><div><div class="invoice-title">Invoice</div><div class="invoice-meta"><strong>' + escapeHtml(sale.invoice) + '</strong><br>Issued ' + formatDate(sale.date) + '</div></div></div><div class="invoice-party"><div><span class="label">Bill to</span><strong>' + escapeHtml(sale.customer) + '</strong><br>' + escapeHtml(sale.phone || '-') + '</div><div><span class="label">Business</span>10A Covel Plaza, opp. Beechwood Estate<br>Malete, Lagos<br>0703 069 5474</div></div><table class="invoice-table"><thead><tr><th>Item</th><th style="text-align:center">Qty</th><th style="text-align:right">Unit price</th><th style="text-align:right">Amount</th></tr></thead><tbody>' + rows + '</tbody></table><div class="invoice-total"><div><span>Total</span><span>' + money.format(sale.total) + '</span></div></div><div class="invoice-note">Payment method: ' + escapeHtml(sale.payment) + '<br>Thank you for choosing Ruach &amp; Terra Reality Ltd.</div>'; $('#invoiceSheet').hidden = false; }
  function csvDownload(filename, rows) { var quote = function (value) { return '"' + String(value == null ? '' : value).replace(/"/g, '""') + '"'; }, blob = new Blob([rows.map(function (row) { return row.map(quote).join(','); }).join('\r\n')], { type: 'text/csv;charset=utf-8' }), link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
  function syncSheet(messageTarget, pendingMessage, successMessage) { setMessage(messageTarget || '#settingsMessage', pendingMessage || 'Saving changes securely...'); return request('/api/admin/sync', { method: 'POST', body: { inventory: db.inventory, sales: db.sales } }).then(function () { setMessage(messageTarget || '#settingsMessage', successMessage || 'Changes securely synced to Google Sheets.'); return true; }).catch(function (error) { if (error.status === 401) { closePortal(); $('#ownerGate').hidden = false; setMessage('#ownerLoginMessage', 'Your session expired. Please sign in again.', true); } setMessage(messageTarget || '#settingsMessage', error.message, true); return false; }); }

  var ownerLaunch = $('#openOwnerPortal');
  if (ownerLaunch) ownerLaunch.addEventListener('click', startOwnerAccess);
  else startOwnerAccess();
  $('#closeOwnerGate').addEventListener('click', function () { $('#ownerGate').hidden = true; });
  $('#ownerLoginForm').addEventListener('submit', function (event) { event.preventDefault(); var button = $('button[type="submit"]', event.currentTarget); button.disabled = true; setMessage('#ownerLoginMessage', 'Signing in...'); request('/api/auth/login', { method: 'POST', body: { email: $('#ownerEmail').value, password: $('#ownerPassword').value } }).then(function () { $('#ownerPassword').value = ''; setMessage('#ownerLoginMessage', ''); openPortal(); }).catch(function (error) { setMessage('#ownerLoginMessage', error.message, true); }).finally(function () { button.disabled = false; }); });
  $('#closeAdminPortal').addEventListener('click', closePortal); $('#ownerLogout').addEventListener('click', signOut); $('#settingsLogout').addEventListener('click', signOut);
  $$('.admin-tab-btn').forEach(function (button) { button.addEventListener('click', function () { showTab(button.dataset.adminTab); }); }); $$('[data-go-tab]').forEach(function (button) { button.addEventListener('click', function () { showTab(button.dataset.goTab); }); });
  $('#addSaleLine').addEventListener('click', function () { addSaleLine(); }); $('#saleLines').addEventListener('input', updateSaleTotals); $('#saleLines').addEventListener('change', updateSaleTotals); $('#saleLines').addEventListener('click', function (event) { if (event.target.classList.contains('remove-sale-line')) { if ($$('.sale-line').length > 1) event.target.closest('.sale-line').remove(); updateSaleTotals(); } });
  $('#saleForm').elements.date.value = today();
  (function () { var grid = $('#inventoryForm .admin-form-grid'); grid.insertAdjacentHTML('beforeend', '<label class="admin-field">Date bought / stocked<input name="stockedDate" type="date" required></label>'); $('#inventoryForm').elements.stockedDate.value = today(); })();
  $('#saleForm').addEventListener('submit', function (event) { event.preventDefault(); var form = event.currentTarget, selected = [], invalid = ''; $$('.sale-line').forEach(function (line) { var product = db.inventory.find(function (item) { return item.id === $('.sale-product', line).value; }), quantity = number($('.sale-quantity', line).value); if (!product) invalid = 'Select a product for every line item.'; else if (quantity < 1 || quantity > product.quantity) invalid = 'Check stock levels - ' + product.name + ' has only ' + product.quantity + ' units available.'; else selected.push({ productId: product.id, name: product.name, quantity: quantity, price: number(product.price), total: quantity * number(product.price) }); }); if (invalid || !selected.length) return setMessage('#saleMessage', invalid || 'Add at least one item to the sale.', true); selected.forEach(function (line) { db.inventory.find(function (item) { return item.id === line.productId; }).quantity -= line.quantity; }); var data = new FormData(form), sale = { id: makeId('sale'), invoice: invoiceNumber(), customer: data.get('customer'), phone: data.get('phone'), payment: data.get('payment'), date: data.get('date'), items: selected, total: selected.reduce(function (sum, line) { return sum + line.total; }, 0), createdAt: new Date().toISOString() }; db.sales.push(sale); saveStore(); form.reset(); form.elements.date.value = today(); renderAll(); syncSheet('#saleMessage', 'Sale saved. Syncing inventory and invoice securely...', 'Sale saved and synced to Google Sheets. Invoice ' + sale.invoice + ' is ready.'); showInvoice(sale.id); });
  $('#inventoryForm').addEventListener('submit', function (event) { event.preventDefault(); var form = event.currentTarget, data = new FormData(form); db.inventory.push({ id: makeId('item'), name: data.get('name').trim(), sku: data.get('sku').trim(), quantity: number(data.get('quantity')), reorderAt: number(data.get('reorderAt')), cost: number(data.get('cost')), price: number(data.get('price')), stockedDate: data.get('stockedDate') || today() }); saveStore(); form.reset(); form.elements.reorderAt.value = 10; form.elements.stockedDate.value = today(); renderAll(); syncSheet('#inventoryMessage', 'Inventory item saved. Syncing securely...', 'Inventory item saved and synced to Google Sheets.'); });
  $('#inventoryBody').addEventListener('click', function (event) { if (!event.target.dataset.restock) return; var item = db.inventory.find(function (record) { return record.id === event.target.dataset.restock; }), amount = Number(window.prompt('How many units of ' + item.name + ' are you adding?', '0')); if (Number.isFinite(amount) && amount > 0) { item.quantity += amount; item.stockedDate = today(); saveStore(); renderAll(); syncSheet('#inventoryMessage', 'Stock updated. Syncing securely...', 'Stock updated and synced to Google Sheets.'); } });
  document.addEventListener('click', function (event) { if (event.target.dataset.invoice) showInvoice(event.target.dataset.invoice); }); $('#closeInvoice').addEventListener('click', function () { $('#invoiceSheet').hidden = true; }); $('#printInvoice').addEventListener('click', function () { window.print(); });
  $('#exportInventory').addEventListener('click', function () { csvDownload('ruach-terra-inventory.csv', [['Name', 'SKU', 'Date Bought / Stocked', 'Quantity', 'Reorder At', 'Cost', 'Selling Price']].concat(db.inventory.map(function (item) { return [item.name, item.sku, item.stockedDate || '', item.quantity, item.reorderAt, item.cost, item.price]; }))); });
  $('#exportSales').addEventListener('click', function () { csvDownload('ruach-terra-sales.csv', [['Invoice', 'Date', 'Customer', 'Phone', 'Payment', 'Items', 'Total']].concat(db.sales.map(function (sale) { return [sale.invoice, sale.date, sale.customer, sale.phone, sale.payment, sale.items.map(function (item) { return item.name + ' x' + item.quantity; }).join('; '), sale.total]; }))); });
})();
