import { PageHero } from '@/components/page-hero';
import { SitePhoto } from '@/components/site-photo';
import { profilePhotos } from '@/content/photography';
import { company, process, team } from '@/content/site';
import { TechnicalPartners } from '@/components/technical-partners';
import { AboutProfileDetails } from '@/components/profile-sections';

const principles = [
  ['Engineering first', 'The source, reserve, pumping method and pipeline route are assessed before production is planned.'],
  ['Safety and reliability', 'Equipment, people and work areas are coordinated for practical site delivery.'],
  ['Client-focused delivery', 'Daily records and agreed sign-off keep information close to the project.'],
];

export default function About() { return <><PageHero eyebrow="About" title="A Nigerian dredging contractor focused on project delivery." copy="Ruach Dredging works on dredging, hydraulic fill and land reclamation in Lagos and Nigeria. Our operating focus is Ibeju-Lekki and Epe." />
  <section className="section section-white"><div className="container grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-start"><div><p className="section-label">Company overview</p><h2 className="section-title">The work is planned from source to placement.</h2><p className="section-intro">Ruach combines owned dredging, pumping, pipeline and support assets with site planning and survey control. The objective is straightforward: move suitable material to the correct location with a documented production process.</p><div className="mt-10 border-t-2 border-ink">{principles.map(([title, copy]) => <article className="grid gap-3 border-b border-line py-6 sm:grid-cols-[180px_1fr]" key={title}><h3 className="font-display text-xl">{title}</h3><p className="text-sm leading-6 text-clay">{copy}</p></article>)}</div></div><SitePhoto src={profilePhotos.barge.src} alt={profilePhotos.barge.alt} className="[&_.photo-frame]:h-[500px]" /></div></section>
  <section className="section section-paper"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-label">Registration</p><h2 className="section-title !text-4xl">Company information.</h2></div><dl className="grid gap-px border border-line bg-line sm:grid-cols-2"><div className="bg-[#f4f1ea] p-6"><dt className="text-xs font-bold uppercase tracking-[.1em] text-clay">Legal name</dt><dd className="mt-3 font-display text-2xl">{company.name}</dd></div><div className="bg-[#f4f1ea] p-6"><dt className="text-xs font-bold uppercase tracking-[.1em] text-clay">Registration</dt><dd className="mt-3 font-display text-2xl">{company.rc}</dd></div><div className="bg-[#f4f1ea] p-6 sm:col-span-2"><dt className="text-xs font-bold uppercase tracking-[.1em] text-clay">Office address</dt><dd className="mt-3 max-w-xl text-base leading-7">{company.address}</dd></div></dl></div></section>
  <TechnicalPartners />
  <section id="process" className="section section-white scroll-mt-24"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-label">Project process</p><h2 className="section-title !text-4xl">How a project runs.</h2><p className="section-intro">The sequence is adapted to the source, pipeline route and placement area.</p></div><ol className="border-t-2 border-ink">{process.map((step, index) => <li key={step} className="grid grid-cols-[54px_1fr] gap-4 border-b border-line py-5"><span className="font-display text-2xl text-rust">{String(index + 1).padStart(2, '0')}</span><span className="pt-1 text-sm font-semibold leading-6">{step}</span></li>)}</ol></div></section>
  <section className="section section-white"><div className="container"><p className="section-label">Leadership</p><h2 className="section-title">Management and technical support.</h2><p className="section-intro">Portrait photography has not been supplied. The team register below is retained without substitute imagery.</p><div className="mt-10 table-scroll" tabIndex={0} role="region" aria-label="Management register"><table className="document-table"><thead><tr><th>Name</th><th>Role</th><th>Responsibility</th></tr></thead><tbody>{team.map(([name, role]) => <tr key={name}><td className="font-semibold text-ink">{name}</td><td>{role}</td><td>{role.includes('HSE') ? 'Health, safety and environment' : role.includes('Finance') ? 'Finance' : role.includes('Legal') ? 'Legal' : role.includes('Admin') ? 'Administration and human resources' : 'Company and project delivery'}</td></tr>)}</tbody></table></div></div></section>
  <AboutProfileDetails /></>; }
