import { PageHero } from '@/components/page-hero';
import { SitePhoto } from '@/components/site-photo';
import { profilePhotos } from '@/content/photography';
import { QualityProfileDetails } from '@/components/profile-sections';

const quality = ['Source and reserve verification', 'Bathymetry and reserve assessment', 'Sieve analysis, Proctor, CBR, Atterberg and salinity testing', 'Daily records and project sign-off'];
const safety = ['Zero-incident policy', 'PPE and toolbox talks', 'SIMOPS awareness', 'NIWA and LASWA compliance', 'Spill response'];
export default function QualityHse() { return <><PageHero eyebrow="Safety and HSE" title="Safety, testing and records at site." copy="The delivery plan includes source verification, testing, operating controls and documented daily work." />
  <section className="section section-white"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><div><p className="section-label">Quality controls</p><h2 className="section-title">Checks before production.</h2><p className="section-intro">Material and site information guide the production plan. Testing and record keeping support decisions during execution.</p><ol className="mt-9 border-t-2 border-ink">{quality.map((item, index) => <li key={item} className="grid grid-cols-[52px_1fr] gap-4 border-b border-line py-5"><span className="font-display text-2xl text-rust">{String(index + 1).padStart(2, '0')}</span><span className="pt-1 text-sm font-semibold leading-6">{item}</span></li>)}</ol></div><SitePhoto src={profilePhotos.discharge.src} alt={profilePhotos.discharge.alt} className="[&_.photo-frame]:h-[500px]" /></div></section>
  <section className="section section-paper"><div className="container grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><SitePhoto src={profilePhotos.crew.src} alt={profilePhotos.crew.alt} className="[&_.photo-frame]:h-[450px]" /><div><p className="section-label">Health, safety and environment</p><h2 className="section-title !text-4xl">Work controls used at site.</h2><div className="mt-8 border-t-2 border-ink">{safety.map((item) => <p key={item} className="border-b border-line py-4 text-sm font-semibold">{item}</p>)}</div><p className="mt-6 text-sm leading-6 text-clay">Requirements are applied according to the project, location and scope of operation.</p></div></div></section>
  <QualityProfileDetails /></>; }
